# Generated by Django 4.2.4 on 2023-08-03 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='code',
            old_name='codeanswer',
            new_name='code_answer',
        ),
    ]
